### ISSUE TITLE
Users Component (Load, Delete, Edit)

### ISSUE THREAD

**Issue by sohaib-baltoro** [baltoroio/shandar#10]
When user goes to http://localhost:3000/settings/users this should load all the users.
There should be a swirly and when data is loaded from backend api the loading icon should disappear
 and list of users should be shown.

When the user clicks on delete icon, this should remove the user object from database
When the user clicks on edit icon this should open up new page.

Hint:
Call api inside ComponentDidMount or UserEffect hook

![UserList](https://user-images.githubusercontent.com/76834333/106392227-f8644d80-6401-11eb-8d90-c89e76e02c9f.png)

**Comment by ShahriyarBaig** [comment]
UserAPi is done other WIP

**Comment by sohaib-baltoro** [comment]
This is not part of current scope
