### ISSUE TITLE
Various AppHeader changes (Add new button, menu item high lighted)

### ISSUE THREAD

**Issue by sohaib-baltoro** [baltoroio/shandar#12]
(Add new button, menu item high lighted)
![AppHeaderChanges](https://user-images.githubusercontent.com/76834333/107216575-0166a780-6a1e-11eb-8850-6a1aa7939ca7.png)

**Comment by ShahriyarBaig** [comment]
Plus Icon Setting pending

**Comment by sohaib-baltoro** [comment]
All the reqs are completed and tested.

Closing this task!
