### ISSUE TITLE
Invite user to workspace changes

### ISSUE THREAD

**Issue by sohaib-baltoro** [baltoroio/shandar#15]
- Move the invite user button from workspace card to users tab
- We will have a users list which will be designed
- For each user add Remove button and functionality. When the user is removed the list should reload.
- We can also remove the user by bulk i.e. selecting more then 1 user. This means we need to design our client logic to handle 1 or more users. We can add check box on each row or check box on header
- 
@URI("tenants/{tenant}/workspaces/{workspaceuuid}/removeusers")

**Comment by sohaib-baltoro** [comment]
![InviteUserModal](https://user-images.githubusercontent.com/76834333/107217691-961dd500-6a1f-11eb-9199-f496719920c9.png)

- Also add invalid email logic for all the emails
- Do the empty email validation before sending to server

**Comment by ShahriyarBaig** [comment]
done -->>Move the invite user button from workspace card to users tab
done --->>We will have a users list which will be designed
WIP--->>For each user add Remove button and functionality. When the user is removed the list should reload.
We can also remove the user by bulk i.e. selecting more then 1 user. This means we need to design our client logic to handle 1 or more users. We can add check box on each row or check box on header

**Comment by sohaib-baltoro** [comment]
UI part is done
