### ISSUE TITLE
Create Application Header Bar

### ISSUE THREAD

**Issue by sohaib-baltoro** [baltoroio/shandar#4]
- In the app header bar 
- App header is present on all the pages
- we should have baltoro branding logo on the left
- There should be a user avatar and drop down arrow
- Add workspace menu on the app bar
- When the user clicks the drop down arrow this should open up a drop down which should have the following menu items

1. Your Profile (/user/:id)
2. Your Organization (/tenant/:id)
3. Settings (/user/:id/settings)
2. Logout (/logout)

App header design:
Baltoro Logo (Left Align) - (Icon: <i class="las la-book"></i>) Workspace Link - Avatar with drop down (Right aligned)

**Comment by ShahriyarBaig** [comment]
start from First step creating header bar  in react

**Comment by ShahriyarBaig** [comment]
App header bar is done 
resolve navdropdowns errors 
add avatar  (also explore avatar react lib )
Add without reload page linking 
clean extras

**Comment by sohaib-baltoro** [comment]
Scope for milestone 1 was completed
