### ISSUE TITLE
Add show/hide password + eye icon and functionality on Login page

### ISSUE THREAD

**Issue by sohaib-baltoro** [baltoroio/shandar#9]

**Comment by sohaib-baltoro** [comment]
![LoginForm_ShowHideEye](https://user-images.githubusercontent.com/76834333/106391954-efbf4780-6400-11eb-83a9-5cabf7cf963e.png)

**Comment by ShahriyarBaig** [comment]
![Screenshot from 2021-02-01 22-24-33](https://user-images.githubusercontent.com/77228975/106494494-4fd6ec00-64dc-11eb-8190-5ae8d3d50d5a.png)

**Comment by ShahriyarBaig** [comment]
done with eye view and UserApi

**Comment by sohaib-baltoro** [comment]
Completed
